import type { Article } from '@/lib/supabase'

/** Supabase 取得失敗時のフォールバック（3テーマ共通） */
export const DUMMY_ARTICLES: Article[] = [
  { id:'1', title:'ChatGPT・Claude・Gemini 徹底比較｜あなたのビジネスに最適なのはどれ？', slug:'chatgpt-claude-gemini-comparison', excerpt:'三大AIツールを料金・機能・得意分野の観点から徹底比較。どれを選べばいいか迷っている方必見。', content:null, thumbnail_url:'https://picsum.photos/seed/zap01/800/450', is_published:true, is_members_only:false, reading_time_minutes:8, view_count:5120, published_at:'2026-05-27', created_at:'2026-05-27', categories:{ name:'ツール比較', slug:'tools', color:'#6B7280' } },
  { id:'2', title:'在庫管理を自動化して在庫ロスを80%削減した小売業のDX事例', slug:'retail-dx-inventory-automation', excerpt:'従業員20名の小売業がAIで在庫管理を自動化し、在庫ロス80%削減・発注業務を週10時間削減した実例。', content:null, thumbnail_url:'https://picsum.photos/seed/zap02/800/450', is_published:true, is_members_only:false, reading_time_minutes:6, view_count:2870, published_at:'2026-05-25', created_at:'2026-05-25', categories:{ name:'DX・業務改善', slug:'dx-improvement', color:'#10B981' } },
  { id:'3', title:'議事録作成をAIで完全自動化する方法｜今日から使えるプロンプト付き', slug:'ai-meeting-minutes-automation', excerpt:'会議のたびに議事録作成に30分〜1時間かかっていませんか？Whisper×ChatGPTを使った完全自動化フローを公開。', content:null, thumbnail_url:'https://picsum.photos/seed/zap03/800/450', is_published:true, is_members_only:false, reading_time_minutes:7, view_count:4380, published_at:'2026-05-26', created_at:'2026-05-26', categories:{ name:'AI活用ガイド', slug:'ai-guide', color:'#3B82F6' } },
  { id:'4', title:'1人社長がChatGPTだけで月商100万を達成した全手順', slug:'solo-president-chatgpt-100man', excerpt:'副業から独立して1年、ChatGPTを活用して月商100万円を達成したフリーランスの実例。使ったプロンプトと業務フローを全公開。', content:null, thumbnail_url:'https://picsum.photos/seed/zap04/800/450', is_published:true, is_members_only:false, reading_time_minutes:10, view_count:6890, published_at:'2026-05-24', created_at:'2026-05-24', categories:{ name:'1人社長・副業・起業', slug:'solo-business', color:'#8B5CF6' } },
  { id:'5', title:'無料AIツールだけで営業資料・SNS投稿・議事録を作る方法【コスト0円】', slug:'free-ai-tools-sales-content', excerpt:'ChatGPT・Canva AI・Notion AIなど無料プランのみで、営業資料・SNS投稿・議事録の3つを全部作る実践ガイド。月額0円でも十分すぎるほど使えます。', content:null, thumbnail_url:'https://picsum.photos/seed/ai009/800/450', is_published:true, is_members_only:false, reading_time_minutes:8, view_count:1840, published_at:'2026-06-01', created_at:'2026-06-01', categories:{ name:'AI活用ガイド', slug:'ai-guide', color:'#3B82F6' } },
  { id:'6', title:'社長がAIを使うと最初に手放せる業務5つ｜経営者目線の導入ガイド', slug:'president-ai-first-tasks', excerpt:'毎日AIを使う経営者が実証済み。社長業の中でAIに任せると劇的に楽になる業務5選と、最初の一歩の踏み出し方を解説します。', content:null, thumbnail_url:'https://picsum.photos/seed/ai010/800/450', is_published:true, is_members_only:false, reading_time_minutes:7, view_count:2340, published_at:'2026-06-01', created_at:'2026-06-01', categories:{ name:'1人社長・副業・起業', slug:'solo-business', color:'#8B5CF6' } },
  { id:'7', title:'中小企業がAI導入で最初にやるべき3つの業務改善', slug:'sme-ai-adoption-first-steps', excerpt:'AI導入に失敗する会社の共通点は「何から始めるか」を間違えること。中小企業が最初に着手すべき3つの業務改善と、無理なく定着させる手順を解説します。', content:null, thumbnail_url:'https://picsum.photos/seed/ai011/800/450', is_published:true, is_members_only:false, reading_time_minutes:6, view_count:1620, published_at:'2026-06-01', created_at:'2026-06-01', categories:{ name:'DX・業務改善', slug:'dx-improvement', color:'#10B981' } },
  { id:'8', title:'席課金 vs 社内Webエージェント｜企業AIコストを最大97%削減する方法【2026年試算】', slug:'enterprise-ai-cost-web-agent-vs-seat', excerpt:'ChatGPT・Claude・Cursor Teamsなど席課金型との比較試算。社内WebにCursor APIを1本通すだけで、5〜100人規模のAIコストを65〜97%削減できる理由を徹底解説します。', content:null, thumbnail_url:'https://picsum.photos/seed/ai012/800/450', is_published:true, is_members_only:false, reading_time_minutes:10, view_count:980, published_at:'2026-06-01', created_at:'2026-06-01', categories:{ name:'実験室・開発ブログ', slug:'lab', color:'#EF4444' } },
]
