import type { Article } from '@/lib/supabase'

/** Supabase 取得失敗時のフォールバック（3テーマ共通） */
export const DUMMY_ARTICLES: Article[] = [
  { id:'9', title:'【速報解説】Claude Fable 5登場──「Mythos-class」史上最高性能モデルは何がすごいのか', slug:'claude-fable-5-overview', excerpt:'Anthropicが公開した過去最高性能のAIモデル「Fable 5」。仕事の任せ方が本質的に変わると言われる新モデルの要点を速報解説。', content:null, thumbnail_url:'https://pbs.twimg.com/media/HIdxS1PbEAA23lz.jpg', is_published:true, is_members_only:false, reading_time_minutes:5, view_count:120, published_at:'2026-06-11T09:40:00Z', created_at:'2026-06-11T09:40:00Z', categories:{ name:'AIニュース・トレンド', slug:'ai-news', color:'#F59E0B' } },
  { id:'10', title:'Claude Fable 5は「高すぎる」のか？──サブエージェント分業でコストを抑える使い方', slug:'claude-fable-5-subagent-strategy', excerpt:'1タスク数万円という衝撃のコスト。それでも最強モデルを実務で使うために、安いモデルで設計し高いモデルで実行する「エージェントチーム」戦略を解説。', content:null, thumbnail_url:'https://pbs.twimg.com/media/HKc9eg5b0AAyQvn.jpg', is_published:true, is_members_only:false, reading_time_minutes:7, view_count:95, published_at:'2026-06-11T09:35:00Z', created_at:'2026-06-11T09:35:00Z', categories:{ name:'AI活用ガイド', slug:'ai-guide', color:'#3B82F6' } },
  { id:'11', title:'Anthropic公式が明かすFable 5の真の使い方──プロンプトではなく「自己修正ループ」を設計せよ【翻訳解説】', slug:'fable-5-self-correction-loops', excerpt:'Anthropic社員Lance Martin氏の技術記事を翻訳解説。ゴール設定・検証サブエージェント・メモリ活用でFable 5の性能を最大限引き出す。', content:null, thumbnail_url:'https://pbs.twimg.com/media/HKYnS0Za8AA_BoV.jpg', is_published:true, is_members_only:false, reading_time_minutes:9, view_count:88, published_at:'2026-06-11T09:30:00Z', created_at:'2026-06-11T09:30:00Z', categories:{ name:'AIニュース・トレンド', slug:'ai-news', color:'#F59E0B' } },
  { id:'12', title:'Anthropicが「31人分のAI社員」を無料公開──中小企業は採用の前に業務のAI化を', slug:'anthropic-31-ai-skills', excerpt:'請求書追跡、契約書レビュー、営業資料作成…実務スキル31種が公式公開。「作業を手伝うAI」から「仕事を任せるAI」への転換点。', content:null, thumbnail_url:'https://pbs.twimg.com/media/HKYAtFVbIAAnxNK.jpg', is_published:true, is_members_only:false, reading_time_minutes:6, view_count:76, published_at:'2026-06-11T09:25:00Z', created_at:'2026-06-11T09:25:00Z', categories:{ name:'DX・業務改善', slug:'dx-improvement', color:'#10B981' } },
  { id:'13', title:'Claude Fable 5×NotebookLM活用術──「究極の頭脳」に「最強の知識」を接続する', slug:'claude-fable-5-notebooklm', excerpt:'史上最強モデルの弱点は「あなたの会社のことを知らない」こと。NotebookLMと組み合わせて自社専用AIに変える活用術。', content:null, thumbnail_url:'https://pbs.twimg.com/media/HKeTevybUAAgzLM.jpg', is_published:true, is_members_only:false, reading_time_minutes:8, view_count:64, published_at:'2026-06-11T09:20:00Z', created_at:'2026-06-11T09:20:00Z', categories:{ name:'ツール比較', slug:'tools', color:'#6B7280' } },
  { id:'14', title:'Claudeを「完全自動運転」にする14ステップ──/loopとRoutinesで自動化スタックを組む【海外記事翻訳】', slug:'claude-autopilot-14-steps', excerpt:'月200ドル払ってChatGPTの有料版のように使っていないか？海外で話題のClaude自動化スタック構築ガイドを日本語で全解説。', content:null, thumbnail_url:'https://pbs.twimg.com/media/HKD8XW4W0AAHp-f.jpg', is_published:true, is_members_only:false, reading_time_minutes:12, view_count:59, published_at:'2026-06-11T09:15:00Z', created_at:'2026-06-11T09:15:00Z', categories:{ name:'AI活用ガイド', slug:'ai-guide', color:'#3B82F6' } },
  { id:'15', title:'上場企業CEOも実践──高コストなFable 5を「一文のプロンプト」で実用的に使う', slug:'kubell-ceo-fable-5-prompt', excerpt:'kubell（旧Chatwork）山本CEOの投稿が話題に。メインセッションは設計とレビューに専念させ、実装はOpus/Sonnetに切り出す分業プロンプトとは。', content:null, thumbnail_url:'https://picsum.photos/seed/fable-prompt/800/450', is_published:true, is_members_only:false, reading_time_minutes:4, view_count:47, published_at:'2026-06-11T09:10:00Z', created_at:'2026-06-11T09:10:00Z', categories:{ name:'AIニュース・トレンド', slug:'ai-news', color:'#F59E0B' } },
  { id:'16', title:'【保存版】AIエージェントで会社を経営する手順──リサーチ・コンテンツ・事務をAIに任せる', slug:'ai-agent-company-management', excerpt:'「AIに任せてるつもりで結局全部自分でやってる」を卒業。東大AIエージェントラボSwarmによる、経営業務をAIに任せる実践手順。', content:null, thumbnail_url:'https://pbs.twimg.com/media/HHtptx_a8AARAev.jpg', is_published:true, is_members_only:false, reading_time_minutes:10, view_count:31, published_at:'2026-06-11T09:05:00Z', created_at:'2026-06-11T09:05:00Z', categories:{ name:'1人社長・副業・起業', slug:'solo-business', color:'#8B5CF6' } },
  { id:'1', title:'ChatGPT・Claude・Gemini 徹底比較｜あなたのビジネスに最適なのはどれ？', slug:'chatgpt-claude-gemini-comparison', excerpt:'三大AIツールを料金・機能・得意分野の観点から徹底比較。どれを選べばいいか迷っている方必見。', content:null, thumbnail_url:'https://picsum.photos/seed/zap01/800/450', is_published:true, is_members_only:false, reading_time_minutes:8, view_count:5120, published_at:'2026-05-27', created_at:'2026-05-27', categories:{ name:'ツール比較', slug:'tools', color:'#6B7280' } },
  { id:'2', title:'在庫管理を自動化して在庫ロスを80%削減した小売業のDX事例', slug:'retail-dx-inventory-automation', excerpt:'従業員20名の小売業がAIで在庫管理を自動化し、在庫ロス80%削減・発注業務を週10時間削減した実例。', content:null, thumbnail_url:'https://picsum.photos/seed/zap02/800/450', is_published:true, is_members_only:false, reading_time_minutes:6, view_count:2870, published_at:'2026-05-25', created_at:'2026-05-25', categories:{ name:'DX・業務改善', slug:'dx-improvement', color:'#10B981' } },
  { id:'3', title:'議事録作成をAIで完全自動化する方法｜今日から使えるプロンプト付き', slug:'ai-meeting-minutes-automation', excerpt:'会議のたびに議事録作成に30分〜1時間かかっていませんか？Whisper×ChatGPTを使った完全自動化フローを公開。', content:null, thumbnail_url:'https://picsum.photos/seed/zap03/800/450', is_published:true, is_members_only:false, reading_time_minutes:7, view_count:4380, published_at:'2026-05-26', created_at:'2026-05-26', categories:{ name:'AI活用ガイド', slug:'ai-guide', color:'#3B82F6' } },
  { id:'4', title:'1人社長がChatGPTだけで月商100万を達成した全手順', slug:'solo-president-chatgpt-100man', excerpt:'副業から独立して1年、ChatGPTを活用して月商100万円を達成したフリーランスの実例。使ったプロンプトと業務フローを全公開。', content:null, thumbnail_url:'https://picsum.photos/seed/zap04/800/450', is_published:true, is_members_only:false, reading_time_minutes:10, view_count:6890, published_at:'2026-05-24', created_at:'2026-05-24', categories:{ name:'1人社長・副業・起業', slug:'solo-business', color:'#8B5CF6' } },
  { id:'5', title:'無料AIツールだけで営業資料・SNS投稿・議事録を作る方法【コスト0円】', slug:'free-ai-tools-sales-content', excerpt:'ChatGPT・Canva AI・Notion AIなど無料プランのみで、営業資料・SNS投稿・議事録の3つを全部作る実践ガイド。月額0円でも十分すぎるほど使えます。', content:null, thumbnail_url:'https://picsum.photos/seed/ai009/800/450', is_published:true, is_members_only:false, reading_time_minutes:8, view_count:1840, published_at:'2026-06-01', created_at:'2026-06-01', categories:{ name:'AI活用ガイド', slug:'ai-guide', color:'#3B82F6' } },
  { id:'6', title:'社長がAIを使うと最初に手放せる業務5つ｜経営者目線の導入ガイド', slug:'president-ai-first-tasks', excerpt:'毎日AIを使う経営者が実証済み。社長業の中でAIに任せると劇的に楽になる業務5選と、最初の一歩の踏み出し方を解説します。', content:null, thumbnail_url:'https://picsum.photos/seed/ai010/800/450', is_published:true, is_members_only:false, reading_time_minutes:7, view_count:2340, published_at:'2026-06-01', created_at:'2026-06-01', categories:{ name:'1人社長・副業・起業', slug:'solo-business', color:'#8B5CF6' } },
  { id:'7', title:'中小企業がAI導入で最初にやるべき3つの業務改善', slug:'sme-ai-adoption-first-steps', excerpt:'AI導入に失敗する会社の共通点は「何から始めるか」を間違えること。中小企業が最初に着手すべき3つの業務改善と、無理なく定着させる手順を解説します。', content:null, thumbnail_url:'https://picsum.photos/seed/ai011/800/450', is_published:true, is_members_only:false, reading_time_minutes:6, view_count:1620, published_at:'2026-06-01', created_at:'2026-06-01', categories:{ name:'DX・業務改善', slug:'dx-improvement', color:'#10B981' } },
  { id:'8', title:'席課金 vs 社内Webエージェント｜企業AIコストを最大97%削減する方法【2026年試算】', slug:'enterprise-ai-cost-web-agent-vs-seat', excerpt:'ChatGPT・Claude・Cursor Teamsなど席課金型との比較試算。社内WebにCursor APIを1本通すだけで、5〜100人規模のAIコストを65〜97%削減できる理由を徹底解説します。', content:null, thumbnail_url:'https://picsum.photos/seed/ai012/800/450', is_published:true, is_members_only:false, reading_time_minutes:10, view_count:980, published_at:'2026-06-01', created_at:'2026-06-01', categories:{ name:'実験室・開発ブログ', slug:'lab', color:'#EF4444' } },
]
